### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by liuxb99** [modelscope/FunClip#103]
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2->funasr>=1.1.2->-r ./requirements.txt (line 4))
  Using cached aliyun-python-sdk-core-2.15.1.tar.gz (443 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\CYLiu99\AppData\Local\Temp\pip-install-l10oqeqh\aliyun-python-sdk-core_9e8cc767cc9847409b8447f4867a2ddd\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by zhenglee1984** [comment]
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe C:\Users\Administrator\AppData\Local\Temp\pip-install-4f748iz5\numpy_1ec75184bd774636839b8493b4faa3b7\vendored-meson\meson\meson.py setup C:\Users\Administrator\AppData\Local\Temp\pip-install-4f748iz5\numpy_1ec75184bd774636839b8493b4faa3b7 C:\Users\Administrator\AppData\Local\Temp\pip-install-4f748iz5\numpy_1ec75184bd774636839b8493b4faa3b7\.mesonpy-unkdbu7x -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Administrator\AppData\Local\Temp\pip-install-4f748iz5\numpy_1ec75184bd774636839b8493b4faa3b7\.mesonpy-unkdbu7x\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-4f748iz5\numpy_1ec75184bd774636839b8493b4faa3b7
      Build dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-4f748iz5\numpy_1ec75184bd774636839b8493b4faa3b7\.mesonpy-unkdbu7x
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `gcc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang-cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `pgcc --version` gave "[WinError 2] 系统找不到指定的文件。"

      A full log can be found at C:\Users\Administrator\AppData\Local\Temp\pip-install-4f748iz5\numpy_1ec75184bd774636839b8493b4faa3b7\.mesonpy-unkdbu7x\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

E:\face\FunClip\FunClip>

**Comment by zhenglee1984** [comment]
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement torch>=1.13 (from versions: none)
ERROR: No matching distribution found for torch>=1.13

**Comment by tuhongwei2022** [comment]
PS C:\Users\tuhon\FunClip> pip install -r ./requirements.txt
Collecting librosa (from -r ./requirements.txt (line 1))
  Using cached librosa-0.10.2.post1-py3-none-any.whl.metadata (8.6 kB)
Collecting soundfile (from -r ./requirements.txt (line 2))
  Using cached soundfile-0.12.1-py2.py3-none-win_amd64.whl.metadata (14 kB)
Collecting scikit-learn>=1.3.2 (from -r ./requirements.txt (line 3))
  Using cached scikit_learn-1.5.2-cp313-cp313-win_amd64.whl.metadata (13 kB)
Collecting funasr>=1.1.2 (from -r ./requirements.txt (line 4))
  Using cached funasr-1.1.14-py3-none-any.whl.metadata (32 kB)
Collecting moviepy (from -r ./requirements.txt (line 5))
  Using cached moviepy-2.1.1-py3-none-any.whl.metadata (6.9 kB)
Collecting numpy==1.26.4 (from -r ./requirements.txt (line 6))
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Program Files\Python313\python.exe C:\Users\tuhon\AppData\Local\Temp\pip-install-eet3sejh\numpy_41354534515241bdb338950656159d23\vendored-meson\meson\meson.py setup C:\Users\tuhon\AppData\Local\Temp\pip-install-eet3sejh\numpy_41354534515241bdb338950656159d23 C:\Users\tuhon\AppData\Local\Temp\pip-install-eet3sejh\numpy_41354534515241bdb338950656159d23\.mesonpy-kj99ivoq -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\tuhon\AppData\Local\Temp\pip-install-eet3sejh\numpy_41354534515241bdb338950656159d23\.mesonpy-kj99ivoq\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\tuhon\AppData\Local\Temp\pip-install-eet3sejh\numpy_41354534515241bdb338950656159d23
      Build dir: C:\Users\tuhon\AppData\Local\Temp\pip-install-eet3sejh\numpy_41354534515241bdb338950656159d23\.mesonpy-kj99ivoq
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `gcc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang-cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `pgcc --version` gave "[WinError 2] 系统找不到指定的文件。"

      A full log can be found at C:\Users\tuhon\AppData\Local\Temp\pip-install-eet3sejh\numpy_41354534515241bdb338950656159d23\.mesonpy-kj99ivoq\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
