### ISSUE TITLE
CompositeVideoClip error

### ISSUE THREAD

**Issue by bengenseo** [modelscope/FunClip#113]
Traceback (most recent call last):
  File "E:\AI\FunClip\fun_env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\AI\FunClip\fun_env\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AI\FunClip\fun_env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\AI\FunClip\fun_env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\AI\FunClip\fun_env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\AI\FunClip\fun_env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\AI\FunClip\fun_env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\AI\FunClip\fun_env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI\FunClip\funclip\launch.py", line 113, in video_clip_addsub
    return audio_clipper.video_clip(
  File "E:\AI\FunClip\funclip\videoclipper.py", line 234, in video_clip
    concate_clip = [video_clip]
TypeError: 'module' object is not callable

**Comment by jaccborn** [comment]
from moviepy.editor import VideoFileClip, concatenate_videoclips,CompositeVideoClip
# from moviepy.video.compositing import CompositeVideoClip

修改一下这个文件 videoclipper.py  最新版CompositeVideoClip的包位置
