### ISSUE TITLE
裁剪+字幕报错

### ISSUE THREAD

**Issue by tangweihui** [modelscope/FunClip#114]
```
Traceback (most recent call last):
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/Users/xxx/Projects/fc/fcenv/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/Users/xxx/Projects/fc/funclip/launch.py", line 158, in AI_clip_subti
    clip_video_file, message, clip_srt = audio_clipper.video_clip(
  File "/Users/xxx/Projects/fc/funclip/videoclipper.py", line 234, in video_clip
    video_clip = CompositeVideoClip([video_clip, subtitles.set_pos(('center','bottom'))])
TypeError: 'module' object is not callable
```
系统： mac

**Comment by gaoleihero** [comment]
可以试试把
from moviepy.video.compositing import CompositeVideoClip  
改成
from moviepy.video.compositing.CompositeVideoClip import CompositeVideoClip

**Comment by tangweihui** [comment]
> 可以试试把 from moviepy.video.compositing import CompositeVideoClip 改成 from moviepy.video.compositing.CompositeVideoClip import CompositeVideoClip

真的可以，膜拜大佬，感谢大佬
