### ISSUE TITLE
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by gpww** [modelscope/FunClip#120]
只要浏览器访问就报错呢?

Running on local URL:  http://127.0.0.1:7861
Running on public URL: https://0d49dcb5463d1abe5b.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\FunClip\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\ProgramData\anaconda3\envs\FunClip\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\FunClip\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\ProgramData\anaconda3\envs\FunClip\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by LauraGPT** [comment]
重新打开。原报告没有得到诊断就被标为 not planned，不符合现在的 issue 处理标准。

请用当前 FunClip `main` 复测，并补充 Python、Gradio、Windows 与 Docker/Conda 版本，说明错误发生在本地 `127.0.0.1` 还是 `gradio.live` share 链接，同时贴完整 traceback。我们会先区分应用错误、Gradio share 连接和 Windows asyncio transport，再决定修复路径。
