### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import 

### ISSUE THREAD

**Issue by godIsAProgrammer** [modelscope/FunClip#90]
选择 demo 视频后，点击识别，识别失败，下面是错误信息，

是 NumPy 版本的问题吗？

错误信息如下：

MoviePy - Writing audio in /private/var/folders/fr/1z0jmnzj16d_z2c68_25w5h40000gn/T/gradio/ec1b96341cbda20c56e7126588746194d6fa382a/E4B8BAE4BB80E4B988E8A681E5A49AE8AFBBE4B9A6EFBC9FE8BF99E698AFE68891E590ACE8BF87E69C80E5A5BDE79A84E7AD94E6A188-E78987E6AEB5.wav
MoviePy - Done.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/gradio/utils.py", line 833, in wrapper
    response = f(*args, **kwargs)
  File "/Users/caoqiye/Project/testspace/FunClip/funclip/launch.py", line 61, in mix_recog
    res_text, res_srt, video_state = video_recog(
  File "/Users/caoqiye/Project/testspace/FunClip/funclip/launch.py", line 46, in video_recog
    return audio_clipper.video_recog(video_input, sd_switch, hotwords, output_dir=output_dir)
  File "/Users/caoqiye/Project/testspace/FunClip/funclip/videoclipper.py", line 154, in video_recog
    wav = librosa.load(audio_file, sr=16000)[0]
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/lazy_loader/__init__.py", line 83, in __getattr__
    attr = getattr(submod, name)
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/lazy_loader/__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/librosa/core/audio.py", line 15, in <module>
    import soxr
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/soxr/__init__.py", line 10, in <module>
    from . import cysoxr
Traceback (most recent call last):
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/gradio/queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/gradio/blocks.py", line 1928, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/gradio/blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/gradio/utils.py", line 833, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/funclip/launch.py", line 61, in mix_recog
    res_text, res_srt, video_state = video_recog(
                                     ^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/funclip/launch.py", line 46, in video_recog
    return audio_clipper.video_recog(video_input, sd_switch, hotwords, output_dir=output_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/funclip/videoclipper.py", line 154, in video_recog
    wav = librosa.load(audio_file, sr=16000)[0]
          ^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/lazy_loader/__init__.py", line 83, in __getattr__
    attr = getattr(submod, name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/lazy_loader/__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/librosa/core/audio.py", line 15, in <module>
    import soxr
  File "/Users/caoqiye/Project/testspace/FunClip/path/to/venv/lib/python3.12/site-packages/soxr/__init__.py", line 10, in <module>
    from . import cysoxr
  File "src/soxr/cysoxr.pyx", line 1, in init soxr.cysoxr
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

**Comment by v3ucn** [comment]
pip uninstall numpy

pip install numpy==1.26.4
